---
# Configure kafka

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ kafka_services_enable }}"
  when: kafka_enable_service
